### ISSUE TITLE
Where do you specify the account name?

### ISSUE THREAD

**Issue by jabbera** [chetansurwade/airflow-xcom-azure-blob#1]
Hi!

This looks like just what I need. I'm confused though. I see the container name coded in the backend, but where do you specify the storage account name?!?

Thanks!

**Comment by chetansurwade** [comment]
> Hi!
> 
> This looks like just what I need. I'm confused though. I see the container name coded in the backend, but where do you specify the storage account name?!?
> 
> Thanks!

![image](https://user-images.githubusercontent.com/29613800/155674520-a25c9744-099b-4df0-98eb-8a21cb7f5f89.png)

I've updated the readme. You'll have to specify a connection to azure blob storage like this. Alternatively you can set AIRFLOW_CONN_WASB_DEFAULT environment variable appropriately.

**Comment by jabbera** [comment]
THANKS!
